### PR TITLE
Breaking

### PR DESCRIPTION
**Pull request by notlee**
See https://github.com/Financial-Times/o-expander/issues/72

### CODE REVIEW

**Comment by origamiserviceuser** [comment]
o-expander bundle size difference from 4.7.1 to a6dfb93c5e04ffbb19e49613ea49082a243f9c78
No bundle size difference found.

**Comment by origamiserviceuser** [comment]
o-expander bundle size difference from 4.7.1 to da5eff2c5d84fff48d03bb0cce2dd0eddda2fdf3
js: 13.67kb increase (4.39kb/gzip)
An insignificant difference was also found for: css (master), css (internal), css (whitelabel)

**Comment by origamiserviceuser** [comment]
o-expander bundle size difference from 4.7.1 to e17dbaed2141c27d61f20f84bf9a0a7c7a47a659
js: 13.65kb increase (4.38kb/gzip)
An insignificant difference was also found for: css (master), css (internal), css (whitelabel)

**Comment by origamiserviceuser** [comment]
o-expander bundle size difference from 4.7.1 to 7656760cbe6086aebefd46c937c0699676860c82
js: 13.5kb increase (4.28kb/gzip)
An insignificant difference was also found for: css (master), css (internal), css (whitelabel)

**Comment by notlee** [comment]
Merging as reviews have happened in other PRs. E.g. https://github.com/Financial-Times/o-expander/pull/77 and https://github.com/Financial-Times/o-expander/pull/79

**Comment by origamiserviceuser** [comment]
o-expander bundle size difference from 4.7.1 to 7369e7fb42fc7a67e94a3e478d45e9880367f4d8
js: 13.49kb increase (4.27kb/gzip)
An insignificant difference was also found for: css (master), css (internal), css (whitelabel)

**Pull request merged**
