### PR TITLE
Refactor JS for a smaller public interface and comprehension.

### PR DESCRIPTION
**Pull request by notlee**
Goals of this PR are to improve code readability (document and make it more like other components), and work toward the major checklist.

**Changes:**
- Improve README documentation.
- Add missing `hidden` expander demo.
- Remove the "mixin" pattern, which conditionally assigned methods
to the prototype.
- Use ESM over CommonJS.
- Add JSDoc to methods.
- Rename the `countSelector` option to `itemSelector`.
- Remove the `toggleSelector`, `rootClassName`, `contentClassName`, 
`toggleClassName` options from the public interface.
- Remove methods `toggleExpander`, `ariaToggles`, `configure`,
`emit`, `hasStateDefined`, and `isRequired` from the public interface.
- Add instance methods `toggle`.
- Add a `createCustom` static method so a custom expander, with
totally custom styles may be created.
- Add `aria-hidden` to collapsible items.
- Replace [`data-o-expander-js`] with `.o-expander--initialized`

**Related issues:**
- https://github.com/Financial-Times/o-expander/issues/68
- https://github.com/Financial-Times/o-expander/issues/72

### CODE REVIEW

**Comment by origamiserviceuser** [comment]
o-expander bundle size difference from 4.7.1 to 65d1ec935c7aa8a98a3cdde94ec55cabab494323
js: 13.67kb increase (4.39kb/gzip)

**Comment by notlee** [comment]
> o-expander bundle size difference from 4.7.1 to [65d1ec9](https://github.com/Financial-Times/o-expander/commit/65d1ec935c7aa8a98a3cdde94ec55cabab494323)
> js: 13.67kb increase (4.39kb/gzip)

Not insignificant. I suspect this is due to:
- More thorough customisation (with`createCustom`).
- More validation.
- More error messages.

**Comment by origamiserviceuser** [comment]
o-expander bundle size difference from 4.7.1 to bd1a4bbb8d2d76b6138690aa6e7117d95a82a708
js: 13.67kb increase (4.40kb/gzip)

**Comment by origamiserviceuser** [comment]
o-expander bundle size difference from 4.7.1 to 9dd010b0f82844a0341a82dc2170b0c035d46b7d
js: 13.67kb increase (4.39kb/gzip)

**Pull request merged**
